name: todolist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  smooth_page_indicator: ^1.2.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  http: ^1.5.0
  cloud_firestore: ^6.0.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/onboardingImages/
    - assets/category/
    - assets/user_icons/

flutter_gen:
  assets:
    enabled: true