// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfwFWJUABa-lQWB3OqEFxnfxAaugdb6Yw',
    appId: '1:1052442666499:web:aa23c303cd6f3bdbbcd036',
    messagingSenderId: '1052442666499',
    projectId: 'todolist-1fd52',
    authDomain: 'todolist-1fd52.firebaseapp.com',
    storageBucket: 'todolist-1fd52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZin_DRa92piKy2nKalLwXYbZV1v-1vk',
    appId: '1:1052442666499:android:8471ad05bd1b16b0bcd036',
    messagingSenderId: '1052442666499',
    projectId: 'todolist-1fd52',
    storageBucket: 'todolist-1fd52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJEJpzr8pXGIK6Bi6S6OcdsH5RUEbFeUc',
    appId: '1:1052442666499:ios:4292919ede62de59bcd036',
    messagingSenderId: '1052442666499',
    projectId: 'todolist-1fd52',
    storageBucket: 'todolist-1fd52.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfwFWJUABa-lQWB3OqEFxnfxAaugdb6Yw',
    appId: '1:1052442666499:web:578bd75fd9deea56bcd036',
    messagingSenderId: '1052442666499',
    projectId: 'todolist-1fd52',
    authDomain: 'todolist-1fd52.firebaseapp.com',
    storageBucket: 'todolist-1fd52.firebasestorage.app',
  );
}
